name: Auto Release

on:
  push:
    branches: [master]

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Zip Extension
        run: zip -r grok-search.zip . -x '*.git*'
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: auto-${{ github.sha }}
          name: Auto Release ${{ github.sha }}
          draft: false
          prerelease: false
          files: grok-search.zip
